Configure DVC in Action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,34 +1,34 @@
+name: Test, lint check and deploy to EC2
+
 on:
   push:
-    branches: "*"
-  pull_request:
-    branches: [main, master]
+    branches:
+      - 183-deploy-with-terraform-and-actions
+
+permissions:
+  id-token: write
+  contents: read
 
 jobs:
-  test-dev:
-    timeout-minutes: 20
+  test:
+    name: "Test"
     runs-on: ubuntu-latest
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          role-to-assume: arn:aws:iam::233044492909:role/skills-tracker-dvc
-          aws-region: eu-west-2
-      - name: Install DVC
-        uses: iterative/setup-dvc@v1
-      - name: Pull data with DVC
-        run: |
-          dvc pull --recursive
-      - name: Start containers
-        run: |
-          bash scripts/test-dev.sh
+    defaults:
+      run:
+        shell: bash
 
-  pre-commit:
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v3
+
+      - name: Configure DVC
+        run: bash scripts/configure_dvc.sh
+
+      - name: Test dev
+        run: bash scripts/test_dev.sh
+
+  lint:
+    name: "Lint"
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -43,3 +43,77 @@ jobs:
       - name: Run pre-commit
         run: |
           poetry run pre-commit run --all-files
+
+  # terraform:
+  #   name: "Terraform"
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       shell: bash
+
+  #   steps:
+  #     - name: Checkout repo
+  #       uses: actions/checkout@v3
+
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         role-to-assume: arn:aws:iam::233044492909:role/SkillsTracker-Terraform
+  #         aws-region: eu-west-2
+
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_wrapper: false
+
+  #     - name: Initialize Terraform
+  #       run: terraform -chdir=deploy/terraform init
+
+  #     - name: Format Terraform
+  #       run: terraform -chdir=deploy/terraform fmt -check
+
+  #     - name: Plan Terraform
+  #       run: terraform -chdir=deploy/terraform plan -input=false
+
+  #     - name: Apply Terraform
+  #       run: terraform -chdir=deploy/terraform apply -auto-approve -input=false
+
+  #     - name: Fetch SSH Key and EIP from Terraform Outputs
+  #       id: fetch-outputs
+  #       run: |
+  #         echo "api_private_key_encoded=$(terraform -chdir=deploy/terraform output -raw private_key | base64 -w0)" >> $GITHUB_ENV
+  #         echo "api_ip=$(terraform -chdir=deploy/terraform output -raw api_ip)" >> $GITHUB_ENV
+
+  #     - name: Configure DVC
+  #       run: bash deploy/configure_dvc.sh
+
+  #     - name: SSH and Install Docker
+  #       run: |
+  #         echo "${{ env.api_private_key_encoded }}" | base64 -d > private_key.pem
+  #         chmod 600 private_key.pem
+  #         attempts=0
+  #         max_attempts=24  # 5-second sleep x 24 = 2 minutes
+  #         while true; do
+  #           if ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.api_ip }} "echo 'ready'"; then
+  #             break  # Exit the loop once SSH succeeds
+  #           fi
+  #           echo "Waiting for EC2 SSH..."
+  #           sleep 5
+  #           attempts=$((attempts+1))
+  #           if [[ "$attempts" -ge "$max_attempts" ]]; then
+  #             echo "Failed to connect to EC2 via SSH after 2 minutes."
+  #             exit 1
+  #           fi
+  #         done
+  #         ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.api_ip }} "mkdir ~/assets"
+  #         ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.api_ip }} "mkdir ~/deploy"
+  #         scp -o StrictHostKeyChecking=no -i private_key.pem deploy/initialise_ec2.sh ubuntu@${{ env.api_ip }}:~/deploy
+  #         scp -o StrictHostKeyChecking=no -i private_key.pem deploy/databases-docker-compose.yml ubuntu@${{ env.api_ip }}:~/deploy
+  #         scp -o StrictHostKeyChecking=no -i private_key.pem deploy/api-docker-compose.yml ubuntu@${{ env.api_ip }}:~/deploy
+  #         scp -o StrictHostKeyChecking=no -i private_key.pem deploy/mongo ubuntu@${{ env.api_ip }}:~/assets
+  #         scp -o StrictHostKeyChecking=no -i private_key.pem deploy/weaviate ubuntu@${{ env.api_ip }}:~/assets
+  #         ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.api_ip }} "chmod +x ~/deploy/initialise_ec2.sh && ~/deploy/initialise_ec2.sh"
+
+  #     - name: Destroy Terraform
+  #       if: always()
+  #       run: terraform -chdir=deploy/terraform destroy -auto-approve
